[package]
name = "mdutils"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "md"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rust_decimal = "1.35"
thiserror = "2.0"
